global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'homelab-exporter'
    static_configs:
      - targets: ['192.168.50.200:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'